#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PennyPincher.Resource", IsApplication=true)]

namespace PennyPincher
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int penny = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int btnAdd = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int btnDelete = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int btnFunds = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int btnRefresh = 2131034138;
			
			// aapt resource value: 0x7f050002
			public const int btnSave = 2131034114;
			
			// aapt resource value: 0x7f050010
			public const int chkIsActive = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int dpFromDate = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int dpToDate = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int hScroll = 2131034118;
			
			// aapt resource value: 0x7f050015
			public const int hldr = 2131034133;
			
			// aapt resource value: 0x7f05000b
			public const int horizontalScrollView1 = 2131034123;
			
			// aapt resource value: 0x7f050013
			public const int lblAccountInfo = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int lblComments = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int lblTransactionDate = 2131034124;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout2 = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int scrollview = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int textView1 = 2131034121;
			
			// aapt resource value: 0x7f050016
			public const int textView10 = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int textView11 = 2131034136;
			
			// aapt resource value: 0x7f050000
			public const int textView2 = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int tvAccountTotal = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int txtAccountName = 2131034113;
			
			// aapt resource value: 0x7f05000f
			public const int txtComments = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int txtFundName = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int txtTitle = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int txtTotal = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int txtTransactionDate = 2131034125;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountEdit = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FundEdit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Funds = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TotalsReport = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TransactionEdit = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Transactions = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
